eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost}:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  datasource:
   password: ${MYSQL_PASSWORD:1234}
   url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:shamshdb}
   username: ${MYSQL_USER:root}
   driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
    ddl-auto: update
   show-sql: true
   properties:
    hibernate:
     dialect: org.hibernate.dialect.MySQL8Dialect   
